/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'readTime' : IDL.Nat,
  'excerpt' : IDL.Text,
});
export const ContactFormEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const FAQEntry = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormEntry)],
      ['query'],
    ),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'readTime' : IDL.Nat,
    'excerpt' : IDL.Text,
  });
  const ContactFormEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const FAQEntry = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  
  return IDL.Service({
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormEntry)],
        ['query'],
      ),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQEntry)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };